### ISSUE TITLE
KEYSTORE_TYPE environment variable replacement bug

### ISSUE THREAD

**Issue by cturczynskyj** [nextgenhealthcare/connect-docker#21]
The entrypoint script is replacing keystore.type in mirth.properties incorrectly. The [replacement](https://github.com/nextgenhealthcare/connect-docker/blob/master/entrypoint.sh#L64) has:

`sed -i "s/^keystore\.keypass\s*=\s*.*\$/keystore.type = ${KEYSTORE_TYPE//\//\\/}/" /opt/connect/conf/mirth.properties`

but it should be:

`sed -i "s/^keystore\.type\s*=\s*.*\$/keystore.type = ${KEYSTORE_TYPE//\//\\/}/" /opt/connect/conf/mirth.properties`

**Comment by pladesma** [comment]
This has been fixed.
