### ISSUE TITLE
[Security] Switch base image for multiple builds

### ISSUE THREAD

**Issue by tonygermano** [nextgenhealthcare/connect-docker#22]
The openjdk docker images are deprecated. See https://hub.docker.com/_/openjdk

https://hub.docker.com/_/adoptopenjdk has also been deprecated in favor of https://hub.docker.com/_/eclipse-temurin/. This image has not been updated in a year.

**Comment by jonbartels** [comment]
I have a local build that appears to work on `eclipse-temurin:17-jre` and `eclipse-temurin:11-jre`.

`eclipse-temurin:17-jre` did require me to add 
```
    environment:
      - "VMOPTIONS=--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED"
 ```
 
 This was due to an error from the premium clustering plugin.

**Comment by tonygermano** [comment]
This was not addressed in the 4.1.1 release that just came out today.

**Comment by jonbartels** [comment]
@narupley - https://hub.docker.com/_/eclipse-temurin

I am running my Mirth containers on `FROM  eclipse-temurin:17-jre` then layering in parts of the MC image. `eclipse-temurin:17-jre` is definitely linux based. It is accessed using `bash` with `docker exec` has `apt`, so it is some Debian variant.

**Comment by tonygermano** [comment]
@narupley https://hub.docker.com/_/eclipse-temurin is the successor of https://hub.docker.com/_/adoptopenjdk, and I think that would make the most sense to use as the default image. It does support Windows, but it also supports Linux on several architectures. That is what most projects use that want a vanilla openjdk.  

For the OpenJ9 builds, you should probably be using https://hub.docker.com/_/ibm-semeru-runtimes

The Azul builds shouldn't need to change.

**Comment by pladesma** [comment]
We pushed the change from openjdk to eclipse-temurin. We'll upload new images on DockerHub with the next MC release.

**Comment by pladesma** [comment]
Oops. Re-opening because we still need to change the adoptopenjdk images, which is coming soon.

**Comment by tonygermano** [comment]
Thanks for the update @pladesma . It would be nice if you would consider repushing at least 4.2.0 with the good base images since that is the currently supported latest version.

**Comment by pladesma** [comment]
We decided to replace both openjdk and adoptopenjdk images with eclipse-temurin. We've updated the image tags for 4.2.0 and pushed new images to DockerHub.
