### ISSUE TITLE
Multi-platform images

### ISSUE THREAD

**Issue by ipavlic** [nextgenhealthcare/connect-docker#24]
`docker image inspect` shows `"Architecture": "amd64"`. This appears to cause issues with Apple M1 hosts. Could the image be built via `buildx` for both `linux/amd64` and `linux/arm64` platforms as described in [Docker's multi platform image instructions](docs.docker.com/build/building/multi-platform)?

**Comment by jas550** [comment]
I opened the issue https://github.com/nextgenhealthcare/connect-docker/issues/15 back in January and was closed even though the issue wasn't resolved. Can we please update the docker containers so that they work on multi platforms.

**Comment by pladesma** [comment]
@jas550 I reopened that issue. I'll close this ticket as a duplicate, and provide a link back to this issue.
