### ISSUE TITLE
How to set configurationmap.location = database from a kubernetes manifest

### ISSUE THREAD

**Issue by IQHT-DGH** [nextgenhealthcare/connect-docker#26]
I have a mirth container stood up in kubernetes, and have managed using the deployment manifest file to setup database access, but I am not able to do the same with the configuration.properties file.  From research I understand that the configuration.properties can be persisted in the database, but I'm unable to find how to pass that setting in the kubernetes deployment manifest.  Any pointers on how I might acheive passing this setting would be gratefully appreciated.

**Comment by pladesma** [comment]
You should be able to set `configurationmap.location = database` using an environment variable when starting the Docker container. The environment variable would be `_MP_CONFIGURATIONMAP_LOCATION='database'`. See [this section](_MP_CONFIGURATIONMAP_LOCATION='database') of the README.

Closing this issue as it's not a defect or feature request.
