### ISSUE TITLE
Why is a specific temurin patch release version specified and not just the latest 17?

### ISSUE THREAD

**Issue by jonbartels** [nextgenhealthcare/connect-docker#29]
Why is the container built from a specific patch release of Temurin 17 and not just the latest patch? 

`eclipse-temurin:17.0.6_10-jre` could just be eclipse-temurin:17-jre and always pull the latest patch release right?

**Comment by pladesma** [comment]
Good point. I don't see why we shouldn't pull the latest patch releases, so we'll make that change.

**Comment by pladesma** [comment]
The change was pushed to the `master` branch.
