### ISSUE TITLE
Dockerhub latest doesn't include latest from this repo

### ISSUE THREAD

**Issue by jensenak** [nextgenhealthcare/connect-docker#3]
I'm running the connect:latest image and running into the error:

`Postgres is unavailable. Aborting.`

After a fair amount of troubleshooting, the issue appears to be that my database username does not match the database name itself. The `entrypoint.sh` script does not include the database name in the connection test it runs, so it tries to connect to a non-existent database matching the username.

This was very hard to troubleshoot because looking at the source here, `entrypoint.sh` _does_ include the database name.

It seems that the nextgenhealthcare/connect:latest image on dockerhub was not actually built with the 3.8.1 tag on this repository?

**Comment by narupley** [comment]
This looks like a mistake on our end, the image pushed to Docker Hub was one commit behind. I re-built and re-pushed the image, try it now!

**Comment by jensenak** [comment]
That did the trick! Much appreciated.
