### ISSUE TITLE
Update of openssl in Dockerfile

### ISSUE THREAD

**Issue by helasz-hu** [nextgenhealthcare/connect-docker#41]
Hi All,
I appreciate very much your great progress in developing mirth-connect.
I would suggest to update the openssl (v3.1.3 -> 3.1.4) in Dockerfile. At the same time I would put the downloaded source files of openssl in a folder different from the root folder.
László

**Comment by pladesma** [comment]
Thanks for the feedback. We'll address this issue in the upcoming 4.4.2 release.

**Comment by helasz-hu** [comment]
I appreciate your prompt action. Please note that testing the Dockerfile (actually in our scenario commandline utilities are needed, so I just do not remove them) I noticed that while ca-certificate package gets removed automatically along with openssl, it does not get reinstalled automatically due to the source compilation approach. I guess there may be cases in which that package would be needed. Marking it as installed manually (sudo apt-mark manual ca-certificates) prior to removing openssl should prevent the automatic uninstallation.
